name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      deploy_mode:
        description: 'Choose deploy mode: Push or Skip Push'
        required: true
        default: 'push'
        options:
          - push
          - skip_push

jobs:
  lint-and-test:
    name: Linting and testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Run Lint
        id: npm-lint
        run: npm run lint

      - name: Run Test
        id: npm-ci-test
        run: npm run test

  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/github-action-school .

      - name: Push to Dockerhub
        if: ${{ github.event.inputs.deploy_mode == 'push' }}
        run: docker push ${{ secrets.DOCKER_USERNAME }}/github-action-school

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - id: deploy
        name: Deploy to EC2
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: us-east-1
          aws_elb_app_port: 3000
