name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      deploy_mode:
        description: 'Choose deploy mode: Push or Skip Push'
        required: true
        default: 'push'
        options:
          - push
          - skip_push

jobs:
  lint-and-test:
    name: Linting and testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Run Lint
        id: npm-lint
        run: npm run lint

      - name: Run Test
        id: npm-ci-test
        run: npm run test
jobs:
  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/github-action-school .

      - name: Push to Dockerhub
        if: ${{ github.event.inputs.deploy_mode == 'push' }}
        run: docker push ${{ secrets.DOCKER_USERNAME }}/github-action-school
